export class Constants{
  public static websiteEndPoint: string = "https://localhost:44343/api"
  //public static websiteEndPoint: string = "http://mostavaahamed-001-site1.ctempurl.com/api";
  public static take: number = 10;
  public static resources: any = {
    en: {
      hello: 'hello',
      le: 'LE',
      rightsReserved: 'all rights reserved',
      logout: "logout",
      login:'login',
      company: 'Mostavaa',
      home: 'Home',
      Categories: 'Categories',
      addMode: 'Add More Departments',
      addModeProducts: 'Add More Products',
      loadMore:'Load More',
      departmentName: 'Name',
      arabicDepartmentName: 'Arabic Name',
      fieldRequired: 'This Field Is Required',
      minLength: 'Characters Length Must be 3 at Least',
      delete: 'Delete',
      add:'Add',
      edit:'Edit',
      deleteConfirmation: 'are you sure you want to delete this?',
      price: 'Price',
      descriptionAr: 'Arabic Description',
      description: 'Description',
      productNameAr: 'Arabic Name',
      productName: 'Name',
      info: 'Information',
      error: 'Error',
      success: 'Success',
      yes: 'Yes',
      no: 'No',
      close: 'Close',
      upload: 'Upload at Least One Image , Max 6 Images',

    },
    ar: {
      hello: 'مرحبا',
      le: 'جنيه',
      rightsReserved: 'جميع الحقوق محفوظة',
      logout: "تسجيل الخروج",
      login:'تسجيل الدخول',
      company: 'Mostavaa',
      home: 'الرئيسية',
      Categories: 'الاقسام',
      addMode: 'اضافة المزيد من الاقسام',
      addModeProducts: 'اضافة المزيد من المنتجات',
      loadMore: 'المزيد',
      departmentName: 'الاسم',
      arabicDepartmentName: 'الاسم باللغة العربية',
      fieldRequired: 'هذا الحقل مطلوب',
      minLength: 'عدد الحروف يجب ان يكون اعلي من 3 حروف',
      delete: 'حذف',
      add: 'اضافة',
      edit: 'تعديل',
      deleteConfirmation: 'هل تريد حذف هذا العنصر؟',
      price: 'السعر',
      descriptionAr: 'الوصف باللغة العربية',
      description: 'الوصف',
      productNameAr: 'الاسم باللغة العربية',
      productName: 'الاسم',
      info: 'تنبيه',
      error: 'خطأ',
      success: 'نجاح',
      yes: 'نعم',
      no: 'لا',
      close: 'اغلاق',
      upload: 'برجاء اختيار صورة على الاقل , 6 صور حد اقصى',
    }
  }
}
